# Generated by Django 3.1.7 on 2021-03-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isDraft',
            field=models.BooleanField(default=True),
        ),
    ]
